# Generated by Django 5.0.6 on 2024-09-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_users_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
