# Generated by Django 5.0.6 on 2024-09-28 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'The field must contain atleast 10 characters')])),
            ],
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
