# Generated by Django 5.0.6 on 2024-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_users_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='message',
            field=models.TextField(),
        ),
    ]
